In [5]:
import numpy as np
import jax.numpy as jnp

from pointscat.forward_problem import compute_foldy_matrix, PointScatteringProblem

from jax.config import config
config.update("jax_enable_x64", True)

In [20]:
amplitudes = np.array([0.1, 2, 1])
locations = np.array([[-3.3, -3.7], [-2.8, 3.5], [3.2, 2.6]])
wave_number = 1
point_scat = PointScatteringProblem(locations, amplitudes, wave_number)

num_scatterers = len(amplitudes)

In [21]:
foldy_mat = point_scat.compute_foldy_matrix()

In [22]:
t_mat = 1/wave_number**2 * (jnp.eye(num_scatterers) - foldy_mat)

In [26]:
print(jnp.abs(t_mat))

[[0.         0.14832531 0.06624926]
 [0.00741627 0.         0.08085001]
 [0.00662493 0.16170002 0.        ]]


In [24]:
print(jnp.abs(jnp.linalg.matrix_power(t_mat, 2)))

[[0.00075622 0.01071251 0.0119921 ]
 [0.00053563 0.0123619  0.00049132]
 [0.00119921 0.00098264 0.01349336]]


In [25]:
print(jnp.abs(jnp.linalg.matrix_power(t_mat, 3)))

[[1.58893573e-04 1.89451128e-03 8.46180380e-04]
 [9.47255642e-05 1.58893573e-04 1.03267105e-03]
 [8.46180380e-05 2.06534210e-03 1.58893573e-04]]
